/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import vista.*;
import controlador.*;
import javax.swing.DefaultListModel;
import modelo.*;

/**
 *
 * @author Jona_RV
 */
public class articulo extends javax.swing.JInternalFrame {

    /**
     * Creates new form articulo
     */
    
    DefaultListModel listaBalon = new DefaultListModel();
    DefaultListModel listaRaqueta = new DefaultListModel();
    DefaultListModel listaRed = new DefaultListModel();
    
    DefaultListModel listaEliminarArticulo = new DefaultListModel();
    
    public articulo() {
        initComponents();
        listBalonList.setModel(listaBalon);
        listRaquetaList.setModel(listaRaqueta);
        listRedList.setModel(listaRed);
        eliminarArticuloList.setModel(listaEliminarArticulo);
        
        cargarComboboxEliminarTipoArticulo();
        llenarListaBalon();
        llenarListaRaqueta();
        llenarListaRed();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        agregarBalonPanel = new javax.swing.JPanel();
        agregarBalonBoton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cantidadBalonSpinner = new javax.swing.JSpinner();
        balonesList = new javax.swing.JScrollPane();
        listBalonList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        tipoBalonComboBox = new javax.swing.JComboBox();
        agregarRaquetaPanel = new javax.swing.JPanel();
        agregarRaquetaBoton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cantidadRaquetaSpinner = new javax.swing.JSpinner();
        raquetasList = new javax.swing.JScrollPane();
        listRaquetaList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        tipoRaquetaComboBox = new javax.swing.JComboBox();
        agregarRedesPanel = new javax.swing.JPanel();
        agregarRedArticuloBTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cantidadRedesSpinner = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        listRedList = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        tipoRedComboBox = new javax.swing.JComboBox();
        eliminarArticuloPanel = new javax.swing.JPanel();
        tipoArticuloComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        tipoArticuloComboBoxEliminar = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        eliminarArticuloList = new javax.swing.JList();
        eliminarArticuloEliminar = new javax.swing.JButton();
        cantidadEliminarSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        cerrarFrameArticulos = new javax.swing.JButton();

        jTabbedPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        agregarBalonBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        agregarBalonBoton.setText("Agregar");
        agregarBalonBoton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agregarBalonBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarBalonBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarBalonBotonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Cantidad:");

        cantidadBalonSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cantidadBalonSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        listBalonList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listBalonList.setName("listaArticulosList"); // NOI18N
        balonesList.setViewportView(listBalonList);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tipo Balon:");

        tipoBalonComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tipoBalonComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bascket", "Futbol", "Voleibol" }));

        javax.swing.GroupLayout agregarBalonPanelLayout = new javax.swing.GroupLayout(agregarBalonPanel);
        agregarBalonPanel.setLayout(agregarBalonPanelLayout);
        agregarBalonPanelLayout.setHorizontalGroup(
            agregarBalonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarBalonPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(agregarBalonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(agregarBalonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidadBalonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoBalonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarBalonBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(balonesList, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        agregarBalonPanelLayout.setVerticalGroup(
            agregarBalonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarBalonPanelLayout.createSequentialGroup()
                .addGroup(agregarBalonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarBalonPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(agregarBalonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tipoBalonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(agregarBalonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadBalonSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addComponent(agregarBalonBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(agregarBalonPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(balonesList, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Agregar Balon", agregarBalonPanel);

        agregarRaquetaBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        agregarRaquetaBoton.setText("Agregar");
        agregarRaquetaBoton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agregarRaquetaBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarRaquetaBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarRaquetaBotonMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Cantidad:");

        cantidadRaquetaSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cantidadRaquetaSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        listRaquetaList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listRaquetaList.setName("listaArticulosList"); // NOI18N
        raquetasList.setViewportView(listRaquetaList);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Tamaño:");

        tipoRaquetaComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tipoRaquetaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pequeño", "Mediano", "Grande" }));

        javax.swing.GroupLayout agregarRaquetaPanelLayout = new javax.swing.GroupLayout(agregarRaquetaPanel);
        agregarRaquetaPanel.setLayout(agregarRaquetaPanelLayout);
        agregarRaquetaPanelLayout.setHorizontalGroup(
            agregarRaquetaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarRaquetaPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(agregarRaquetaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(agregarRaquetaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoRaquetaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadRaquetaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarRaquetaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(raquetasList, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        agregarRaquetaPanelLayout.setVerticalGroup(
            agregarRaquetaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarRaquetaPanelLayout.createSequentialGroup()
                .addGroup(agregarRaquetaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarRaquetaPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(agregarRaquetaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tipoRaquetaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(agregarRaquetaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadRaquetaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addComponent(agregarRaquetaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(agregarRaquetaPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(raquetasList, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Agregar Raqueta", agregarRaquetaPanel);

        agregarRedArticuloBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        agregarRedArticuloBTN.setText("Agregar");
        agregarRedArticuloBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agregarRedArticuloBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarRedArticuloBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarRedArticuloBTNMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Cantidad:");

        cantidadRedesSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cantidadRedesSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        listRedList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listRedList.setName("listaArticulosList"); // NOI18N
        jScrollPane3.setViewportView(listRedList);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tipo Red:");

        tipoRedComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tipoRedComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tennis", "Voleibol", "Cancha" }));

        javax.swing.GroupLayout agregarRedesPanelLayout = new javax.swing.GroupLayout(agregarRedesPanel);
        agregarRedesPanel.setLayout(agregarRedesPanelLayout);
        agregarRedesPanelLayout.setHorizontalGroup(
            agregarRedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarRedesPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(agregarRedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addGroup(agregarRedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidadRedesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoRedComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarRedArticuloBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        agregarRedesPanelLayout.setVerticalGroup(
            agregarRedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarRedesPanelLayout.createSequentialGroup()
                .addGroup(agregarRedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarRedesPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(agregarRedesPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(agregarRedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tipoRedComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(agregarRedesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadRedesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(37, 37, 37)
                        .addComponent(agregarRedArticuloBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Agregar Redes", agregarRedesPanel);

        tipoArticuloComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tipoArticuloComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Balon", "Raqueta", "Red" }));
        tipoArticuloComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoArticuloComboBoxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Seleccione el Articulo:");

        tipoArticuloComboBoxEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tipoArticuloComboBoxEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoArticuloComboBoxEliminarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Seleccione el tipo Articulo:");

        eliminarArticuloList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        eliminarArticuloList.setName("listaArticulosList"); // NOI18N
        jScrollPane4.setViewportView(eliminarArticuloList);

        eliminarArticuloEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        eliminarArticuloEliminar.setText("Eliminar");
        eliminarArticuloEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarArticuloEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarArticuloEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarArticuloEliminarMouseClicked(evt);
            }
        });

        cantidadEliminarSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Cantidad:");

        javax.swing.GroupLayout eliminarArticuloPanelLayout = new javax.swing.GroupLayout(eliminarArticuloPanel);
        eliminarArticuloPanel.setLayout(eliminarArticuloPanelLayout);
        eliminarArticuloPanelLayout.setHorizontalGroup(
            eliminarArticuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarArticuloPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(eliminarArticuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(eliminarArticuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminarArticuloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoArticuloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoArticuloComboBoxEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadEliminarSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        eliminarArticuloPanelLayout.setVerticalGroup(
            eliminarArticuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarArticuloPanelLayout.createSequentialGroup()
                .addGroup(eliminarArticuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eliminarArticuloPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(eliminarArticuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tipoArticuloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(eliminarArticuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tipoArticuloComboBoxEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(eliminarArticuloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cantidadEliminarSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(eliminarArticuloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(eliminarArticuloPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Eliminar Articulo", eliminarArticuloPanel);

        cerrarFrameArticulos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cerrarFrameArticulos.setText("Cerrar");
        cerrarFrameArticulos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cerrarFrameArticulos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarFrameArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarFrameArticulosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarFrameArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrarFrameArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane4.getAccessibleContext().setAccessibleName("Agregar Raqueta");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarFrameArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarFrameArticulosMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarFrameArticulosMouseClicked

    private void agregarBalonBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarBalonBotonMouseClicked
        // TODO add your handling code here:
        String tipo = tipoBalonComboBox.getSelectedItem().toString();
        int cantidad = Integer.parseInt(cantidadBalonSpinner.getValue().toString());
                
        Articulo art = new Articulo("balon", tipo, cantidad);
        Progra4.cenDep.getListaArticulos().add(art);
        
        metodosBase met = new metodosBase();
        met.insertarArticuloBase("Balon", tipo, cantidad);
        cargarComboboxEliminarTipoArticulo();
        listaBalon.clear();
        llenarListaBalon();
    }//GEN-LAST:event_agregarBalonBotonMouseClicked

    private void agregarRaquetaBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarRaquetaBotonMouseClicked
        // TODO add your handling code here:
        String tipo = tipoRaquetaComboBox.getSelectedItem().toString();
        int cantidad = Integer.parseInt(cantidadRaquetaSpinner.getValue().toString());
                
        Articulo art = new Articulo("Raqueta", tipo, cantidad);
        Progra4.cenDep.getListaArticulos().add(art);
        
        metodosBase met = new metodosBase();
        met.insertarArticuloBase("Raqueta", tipo, cantidad);
        cargarComboboxEliminarTipoArticulo();
        llenarListaRaqueta();
    }//GEN-LAST:event_agregarRaquetaBotonMouseClicked

    private void agregarRedArticuloBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarRedArticuloBTNMouseClicked
        // TODO add your handling code here:
        String tipo = tipoRedComboBox.getSelectedItem().toString();
        int cantidad = Integer.parseInt(cantidadRedesSpinner.getValue().toString());
                
        Articulo art = new Articulo("Red", tipo, cantidad);
        Progra4.cenDep.getListaArticulos().add(art);
        
        metodosBase met = new metodosBase();
        met.insertarArticuloBase("Red", tipo, cantidad);
        cargarComboboxEliminarTipoArticulo();
        llenarListaRed();
    }//GEN-LAST:event_agregarRedArticuloBTNMouseClicked

    private void tipoArticuloComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoArticuloComboBoxActionPerformed
        // TODO add your handling code here:
        tipoArticuloComboBoxEliminar.removeAllItems();
        int tam = Progra4.cenDep.getListaArticulos().size();
        
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                if(tipoArticuloComboBox.getSelectedItem().equals(Progra4.cenDep.getListaArticulos().get(i).getNombre()))
                {
                    tipoArticuloComboBoxEliminar.addItem(Progra4.cenDep.getListaArticulos().get(i).getTipo());
                }                
            }
        } 
    }//GEN-LAST:event_tipoArticuloComboBoxActionPerformed

    private void tipoArticuloComboBoxEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoArticuloComboBoxEliminarActionPerformed
        // TODO add your handling code here:
        int tam = Progra4.cenDep.getListaArticulos().size();
        listaEliminarArticulo.clear();
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                if(tipoArticuloComboBoxEliminar.getSelectedIndex() >= 0){
                    if((tipoArticuloComboBoxEliminar.getSelectedItem().equals(Progra4.cenDep.getListaArticulos().get(i).getTipo()))
                            & (tipoArticuloComboBox.getSelectedItem().equals(Progra4.cenDep.getListaArticulos().get(i).getNombre())))
                    {
                        listaEliminarArticulo.addElement("Nombre: "+Progra4.cenDep.getListaArticulos().get(i).getNombre());
                        listaEliminarArticulo.addElement("Tipo: "+Progra4.cenDep.getListaArticulos().get(i).getTipo());
                        listaEliminarArticulo.addElement("Cantidad: "+Progra4.cenDep.getListaArticulos().get(i).getCantidad());

                        listaEliminarArticulo.addElement("");
                        listaEliminarArticulo.addElement(" ***************************** ");
                    }        
                }
            }
        }
    }//GEN-LAST:event_tipoArticuloComboBoxEliminarActionPerformed

    private void eliminarArticuloEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarArticuloEliminarMouseClicked
        // TODO add your handling code here:
        
        String nombre = tipoArticuloComboBox.getSelectedItem().toString();
        String tipo = tipoArticuloComboBoxEliminar.getSelectedItem().toString();
        int cantidad = Integer.parseInt(cantidadEliminarSpinner.getValue().toString());
        
        metodosBase met = new metodosBase();
        met.eliminarArticuloBase(nombre, tipo, cantidad);
        llenarListaBalon();
        llenarListaRaqueta();
        llenarListaRed();
        llenarListaEliminarArticulo();
        cantidadEliminarSpinner.setValue(0);
    }//GEN-LAST:event_eliminarArticuloEliminarMouseClicked

    
    
    public  void cargarComboboxEliminarTipoArticulo(){
        tipoArticuloComboBoxEliminar.removeAllItems();
        int tam = Progra4.cenDep.getListaArticulos().size();
        
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                if(tipoArticuloComboBox.getSelectedItem().equals(Progra4.cenDep.getListaArticulos().get(i).getNombre()))
                {
                    tipoArticuloComboBoxEliminar.addItem(Progra4.cenDep.getListaArticulos().get(i).getTipo());
                }                
             }
        } 
    }
    
    public void llenarListaBalon(){
        
        int tam = Progra4.cenDep.getListaArticulos().size();
        listaBalon.clear();
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                if(Progra4.cenDep.getListaArticulos().get(i).getNombre().equals("Balon"))
                {
                    listaBalon.addElement("Nombre: "+Progra4.cenDep.getListaArticulos().get(i).getNombre());
                    listaBalon.addElement("Tipo: "+Progra4.cenDep.getListaArticulos().get(i).getTipo());
                    listaBalon.addElement("Cantidad: "+Progra4.cenDep.getListaArticulos().get(i).getCantidad());
                    
                    listaBalon.addElement("");
                    listaBalon.addElement(" ***************************** ");
                }                
             }
        }
    }
    
    public void llenarListaRaqueta(){
        
        listaRaqueta.clear();
        int tam = Progra4.cenDep.getListaArticulos().size();
        
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                if(Progra4.cenDep.getListaArticulos().get(i).getNombre().equals("Raqueta"))
                {
                    listaRaqueta.addElement("Nombre: "+Progra4.cenDep.getListaArticulos().get(i).getNombre());
                    listaRaqueta.addElement("Tipo: "+Progra4.cenDep.getListaArticulos().get(i).getTipo());
                    listaRaqueta.addElement("Cantidad: "+Progra4.cenDep.getListaArticulos().get(i).getCantidad());
                    
                    listaRaqueta.addElement("");
                    listaRaqueta.addElement(" **************************** ");
                }                
             }
        }
    }
    
    public void llenarListaRed(){
        
        listaRed.clear();
        int tam = Progra4.cenDep.getListaArticulos().size();
        
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                if(Progra4.cenDep.getListaArticulos().get(i).getNombre().equals("Red"))
                {
                    listaRed.addElement("Nombre: "+Progra4.cenDep.getListaArticulos().get(i).getNombre());
                    listaRed.addElement("Tipo: "+Progra4.cenDep.getListaArticulos().get(i).getTipo());
                    listaRed.addElement("Cantidad: "+Progra4.cenDep.getListaArticulos().get(i).getCantidad());
                    
                    listaRed.addElement("");
                    listaRed.addElement(" ***************************** ");
                }                
             }
        }
    }
    
    public void llenarListaEliminarArticulo(){
        
        int tam = Progra4.cenDep.getListaArticulos().size();
        listaEliminarArticulo.clear();
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                if(tipoArticuloComboBoxEliminar.getSelectedIndex() >= 0){
                    if((tipoArticuloComboBoxEliminar.getSelectedItem().equals(Progra4.cenDep.getListaArticulos().get(i).getTipo()))
                            & (tipoArticuloComboBox.getSelectedItem().equals(Progra4.cenDep.getListaArticulos().get(i).getNombre())))
                    {
                        listaEliminarArticulo.addElement("Nombre: "+Progra4.cenDep.getListaArticulos().get(i).getNombre());
                        listaEliminarArticulo.addElement("Tipo: "+Progra4.cenDep.getListaArticulos().get(i).getTipo());
                        listaEliminarArticulo.addElement("Cantidad: "+Progra4.cenDep.getListaArticulos().get(i).getCantidad());

                        listaEliminarArticulo.addElement("");
                        listaEliminarArticulo.addElement(" ***************************** ");
                    }        
                }
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBalonBoton;
    private javax.swing.JPanel agregarBalonPanel;
    private javax.swing.JButton agregarRaquetaBoton;
    private javax.swing.JPanel agregarRaquetaPanel;
    private javax.swing.JButton agregarRedArticuloBTN;
    private javax.swing.JPanel agregarRedesPanel;
    private javax.swing.JScrollPane balonesList;
    private javax.swing.JSpinner cantidadBalonSpinner;
    private javax.swing.JSpinner cantidadEliminarSpinner;
    private javax.swing.JSpinner cantidadRaquetaSpinner;
    private javax.swing.JSpinner cantidadRedesSpinner;
    private javax.swing.JButton cerrarFrameArticulos;
    private javax.swing.JButton eliminarArticuloEliminar;
    private javax.swing.JList eliminarArticuloList;
    private javax.swing.JPanel eliminarArticuloPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JList listBalonList;
    private javax.swing.JList listRaquetaList;
    private javax.swing.JList listRedList;
    private javax.swing.JScrollPane raquetasList;
    private javax.swing.JComboBox tipoArticuloComboBox;
    private javax.swing.JComboBox tipoArticuloComboBoxEliminar;
    private javax.swing.JComboBox tipoBalonComboBox;
    private javax.swing.JComboBox tipoRaquetaComboBox;
    private javax.swing.JComboBox tipoRedComboBox;
    // End of variables declaration//GEN-END:variables
}
