/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;
import javax.swing.DefaultListModel;
import modelo.*;
import vista.*;

/**
 *
 * @author Jona_RV
 */
public class instalaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form instalaciones
     */
    DefaultListModel list = new DefaultListModel();
    
    public instalaciones() {
        initComponents();
        listEliminarInstalacion.setModel(list);
        
        cargarComboboxEliminarInstalacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrarFrameInstalacion = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tFCanttFNombrePiscina = new javax.swing.JTextField();
        tFDimensionesPiscina = new javax.swing.JTextField();
        tFCaracteristicasPiscina = new javax.swing.JTextField();
        tFNombrePiscina = new javax.swing.JTextField();
        tFProdundidadPiscina = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        bTagregarPiscina = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tFNombrePista = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tFCaracteristicastFNombrePista = new javax.swing.JTextField();
        tFDimensionestFNombrePista = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tFCanttFNombrePista = new javax.swing.JTextField();
        bTagregarPista = new javax.swing.JButton();
        tFCantCancha = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tFNombreCancha = new javax.swing.JTextField();
        tFCaracteristicasCancha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tFDimensionesCancha = new javax.swing.JTextField();
        tFtipoCancha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bTagregarCancha = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tFNombreGym = new javax.swing.JTextField();
        tFCaracteristicasGym = new javax.swing.JTextField();
        tFDimensionesGym = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tFCantGym = new javax.swing.JTextField();
        bTagregarGimnasio = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        eliminarTipoInstalacionjComboBox = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        eliminarInstalacionjComboBox = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        eliminarInstalacionBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEliminarInstalacion = new javax.swing.JList();

        setTitle("Instalaciones");

        cerrarFrameInstalacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cerrarFrameInstalacion.setText("Cerrar");
        cerrarFrameInstalacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cerrarFrameInstalacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarFrameInstalacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarFrameInstalacionMouseClicked(evt);
            }
        });

        jLabel13.setText("Nombre:");

        jLabel14.setText("Caracteristicas:");

        jLabel15.setText("Dimensiones:");

        jLabel16.setText("Cantidad de Carriles:");

        tFCanttFNombrePiscina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tFDimensionesPiscina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tFCaracteristicasPiscina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tFNombrePiscina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tFNombrePiscina.setName(""); // NOI18N

        tFProdundidadPiscina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel17.setText("Profundidad:");

        bTagregarPiscina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bTagregarPiscina.setText("Agregar");
        bTagregarPiscina.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bTagregarPiscina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTagregarPiscinaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bTagregarPiscina, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tFNombrePiscina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tFCaracteristicasPiscina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tFCanttFNombrePiscina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tFDimensionesPiscina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tFProdundidadPiscina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tFNombrePiscina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tFCaracteristicasPiscina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFDimensionesPiscina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tFCanttFNombrePiscina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tFProdundidadPiscina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(bTagregarPiscina, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Piscinas", jPanel2);

        tFNombrePista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tFNombrePista.setName(""); // NOI18N

        jLabel9.setText("Nombre:");

        jLabel10.setText("Caracteristicas:");

        tFCaracteristicastFNombrePista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tFDimensionestFNombrePista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setText("Dimensiones:");

        jLabel12.setText("Cantidad de Carriles:");

        tFCanttFNombrePista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bTagregarPista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bTagregarPista.setText("Agregar");
        bTagregarPista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bTagregarPista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTagregarPistaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bTagregarPista, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tFNombrePista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tFCaracteristicastFNombrePista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tFCanttFNombrePista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tFDimensionestFNombrePista, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tFNombrePista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tFCaracteristicastFNombrePista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFDimensionestFNombrePista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tFCanttFNombrePista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(bTagregarPista, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pistas", jPanel3);

        jLabel5.setText("Nombre:");

        tFNombreCancha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tFNombreCancha.setName(""); // NOI18N

        tFCaracteristicasCancha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setText("Caracteristicas:");

        jLabel7.setText("Dimensiones:");

        tFDimensionesCancha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tFtipoCancha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setText("Tipo de Cancha:");

        bTagregarCancha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bTagregarCancha.setText("Agregar");
        bTagregarCancha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bTagregarCancha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTagregarCanchaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tFCantCanchaLayout = new javax.swing.GroupLayout(tFCantCancha);
        tFCantCancha.setLayout(tFCantCanchaLayout);
        tFCantCanchaLayout.setHorizontalGroup(
            tFCantCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tFCantCanchaLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(tFCantCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bTagregarCancha, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tFCantCanchaLayout.createSequentialGroup()
                        .addGroup(tFCantCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(36, 36, 36)
                        .addGroup(tFCantCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(tFCantCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(tFCantCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tFNombreCancha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tFCaracteristicasCancha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tFtipoCancha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tFDimensionesCancha, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        tFCantCanchaLayout.setVerticalGroup(
            tFCantCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tFCantCanchaLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(tFCantCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tFNombreCancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(tFCantCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tFCaracteristicasCancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tFCantCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFDimensionesCancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(tFCantCanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tFtipoCancha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(bTagregarCancha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancha", tFCantCancha);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Caracteristicas:");

        jLabel3.setText("Dimensiones:");

        tFNombreGym.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tFNombreGym.setName(""); // NOI18N

        tFCaracteristicasGym.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tFDimensionesGym.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setText("Cantidad Maquinas:");

        tFCantGym.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bTagregarGimnasio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bTagregarGimnasio.setText("Agregar");
        bTagregarGimnasio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bTagregarGimnasio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTagregarGimnasioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bTagregarGimnasio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tFCaracteristicasGym, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tFNombreGym, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tFDimensionesGym, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tFCantGym, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tFNombreGym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tFCaracteristicasGym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFDimensionesGym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tFCantGym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(bTagregarGimnasio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jTabbedPane1.addTab("Gimnasio", jPanel1);

        eliminarTipoInstalacionjComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        eliminarTipoInstalacionjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Piscinas", "Pista", "Cancha", "Gym" }));
        eliminarTipoInstalacionjComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarTipoInstalacionjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTipoInstalacionjComboBoxActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Selecciones la Instalacion:");

        eliminarInstalacionjComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        eliminarInstalacionjComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarInstalacionjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarInstalacionjComboBoxActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Seleccione el Tipo Instalacion:");

        eliminarInstalacionBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        eliminarInstalacionBTN.setText("Eliminar");
        eliminarInstalacionBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarInstalacionBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarInstalacionBTNMouseClicked(evt);
            }
        });

        listEliminarInstalacion.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listEliminarInstalacion);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eliminarTipoInstalacionjComboBox, 0, 141, Short.MAX_VALUE)
                            .addComponent(eliminarInstalacionjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addComponent(eliminarInstalacionBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarTipoInstalacionjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(eliminarInstalacionBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarInstalacionjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cerrarFrameInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrarFrameInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarFrameInstalacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarFrameInstalacionMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarFrameInstalacionMouseClicked

    private void bTagregarPiscinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTagregarPiscinaMouseClicked
        // TODO add your handling code here:
        
        eliminarInstalacionjComboBox.removeAllItems();
        int profundidad = Integer.parseInt(tFProdundidadPiscina.getText());
        int carriles = Integer.parseInt(tFCanttFNombrePiscina.getText());
        String nombre = tFNombrePiscina.getText();
        String dimension = tFDimensionesPiscina.getText();
        String caracteris = tFCaracteristicasPiscina.getText();
        
        Piscinas pis = new Piscinas(profundidad, carriles, nombre, caracteris, dimension);
        Progra4.cenDep.getListaInstalaciones().add(pis);
        
        metodosBase met = new metodosBase();
        met.insertarPiscinaBase(nombre, carriles, profundidad, dimension, caracteris);
        
        cargarComboboxEliminarInstalacion();
        
        tFCanttFNombrePiscina.setText("");
        tFCaracteristicasPiscina.setText("");
        tFNombrePiscina.setText("");
        tFProdundidadPiscina.setText("");
        tFDimensionesPiscina.setText("");
    }//GEN-LAST:event_bTagregarPiscinaMouseClicked

    private void bTagregarPistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTagregarPistaMouseClicked
        // TODO add your handling code here:
        
        int carriles = Integer.parseInt(tFCanttFNombrePista.getText());
        String nombre = tFNombrePista.getText();
        String dimension = tFDimensionestFNombrePista.getText();
        String caracteris = tFCaracteristicastFNombrePista.getText();
        
        Pista pist = new Pista(carriles, nombre, caracteris, dimension);
        Progra4.cenDep.getListaInstalaciones().add(pist);
        
        metodosBase met = new metodosBase();
        met.insertarPistaBase(nombre, carriles, dimension, caracteris);
        
        cargarComboboxEliminarInstalacion();
        
        tFCanttFNombrePista.setText("");
        tFCaracteristicastFNombrePista.setText("");
        tFDimensionestFNombrePista.setText("");
        tFCanttFNombrePista.setText("");
    }//GEN-LAST:event_bTagregarPistaMouseClicked

    private void bTagregarCanchaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTagregarCanchaMouseClicked
        // TODO add your handling code here:
        String tipo = tFtipoCancha.getText();
        String nombre = tFNombreCancha.getText();
        String dimension = tFDimensionesCancha.getText();
        String caracteris = tFCaracteristicasCancha.getText();
        
        Cancha canch = new Cancha(tipo, nombre, caracteris, dimension);
        Progra4.cenDep.getListaInstalaciones().add(canch);
        
        metodosBase met =  new metodosBase();
        met.insertarCanchaBase(nombre, tipo, dimension, caracteris);
        
        cargarComboboxEliminarInstalacion();
        
        tFDimensionesCancha.setText("");
        tFCaracteristicasCancha.setText("");
        tFNombreCancha.setText("");
        tFtipoCancha.setText("");
    }//GEN-LAST:event_bTagregarCanchaMouseClicked

    private void bTagregarGimnasioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTagregarGimnasioMouseClicked
        // TODO add your handling code here:
        int cantMaquinas = Integer.parseInt(tFCantGym.getText());
        String nombre = tFNombreGym.getText();
        String dimension = tFDimensionesGym.getText();
        String caracteris = tFCaracteristicasGym.getText();
        
        Gym gym = new Gym(cantMaquinas, nombre, caracteris, dimension);
        Progra4.cenDep.getListaInstalaciones().add(gym);
        
        metodosBase met = new metodosBase();
        met.insertarGymBase(nombre, cantMaquinas, dimension, caracteris);
        
        cargarComboboxEliminarInstalacion();
        
        tFCantGym.setText("");
        tFCaracteristicasGym.setText("");
        tFDimensionesGym.setText("");
        tFNombreGym.setText("");
    }//GEN-LAST:event_bTagregarGimnasioMouseClicked

    private void eliminarTipoInstalacionjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTipoInstalacionjComboBoxActionPerformed
        // TODO add your handling code here:
        eliminarInstalacionjComboBox.removeAllItems();
        int tam = Progra4.cenDep.getListaInstalaciones().size();
        
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                String[] nombreClase = Progra4.cenDep.getListaInstalaciones().get(i).getClass().getName().split("controlador.");
                if(nombreClase[1].equals(eliminarTipoInstalacionjComboBox.getSelectedItem()))
                {
                    eliminarInstalacionjComboBox.addItem(Progra4.cenDep.getListaInstalaciones().get(i).getNombre());
                }                
             }
        }        
    }//GEN-LAST:event_eliminarTipoInstalacionjComboBoxActionPerformed

    private void eliminarInstalacionBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarInstalacionBTNMouseClicked
        // TODO add your handling code here:
        
        for(int i = 0; i < Progra4.cenDep.getListaInstalaciones().size(); i++){
            String[] nombreClase = Progra4.cenDep.getListaInstalaciones().get(i).getClass().getName().split("controlador.");
            if(nombreClase[1].equals(eliminarTipoInstalacionjComboBox.getSelectedItem()))
            {
                if(eliminarInstalacionjComboBox.getSelectedItem().equals(Progra4.cenDep.getListaInstalaciones().get(i).getNombre())){
                    
                    metodosBase met = new metodosBase();
                    met.eliminarInstalacionBase(nombreClase[1], Progra4.cenDep.getListaInstalaciones().get(i).getNombre());
                    cargarComboboxEliminarInstalacion();
                }                
            }                
         }
        
    }//GEN-LAST:event_eliminarInstalacionBTNMouseClicked

    private void eliminarInstalacionjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarInstalacionjComboBoxActionPerformed
        // TODO add your handling code here:
        list.clear();
        if(eliminarInstalacionjComboBox.getSelectedIndex() >= 0){        
            for(int i = 0; i < Progra4.cenDep.getListaInstalaciones().size(); i++){
                if(eliminarInstalacionjComboBox.getSelectedItem().equals(Progra4.cenDep.getListaInstalaciones().get(i).getNombre())){
                    list.addElement("Nombre:  "+(Progra4.cenDep.getListaInstalaciones().get(i).getNombre()));
                    list.addElement("Caracteristicas:  "+(Progra4.cenDep.getListaInstalaciones().get(i).getCaracteristicas()));
                    list.addElement("Dimensiones:  "+(Progra4.cenDep.getListaInstalaciones().get(i).getDimesion()));
                }              
             }
        }
    }//GEN-LAST:event_eliminarInstalacionjComboBoxActionPerformed

    
    public void cargarComboboxEliminarInstalacion() {
        
        eliminarInstalacionjComboBox.removeAllItems();
        int tam = Progra4.cenDep.getListaInstalaciones().size();
        
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                String[] nombreClase = Progra4.cenDep.getListaInstalaciones().get(i).getClass().getName().split("controlador.");
                if(nombreClase[1].equals(eliminarTipoInstalacionjComboBox.getSelectedItem()))
                {
                    eliminarInstalacionjComboBox.addItem(Progra4.cenDep.getListaInstalaciones().get(i).getNombre());
                }                
             }
        }                
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTagregarCancha;
    private javax.swing.JButton bTagregarGimnasio;
    private javax.swing.JButton bTagregarPiscina;
    private javax.swing.JButton bTagregarPista;
    private javax.swing.JButton cerrarFrameInstalacion;
    private javax.swing.JButton eliminarInstalacionBTN;
    private javax.swing.JComboBox eliminarInstalacionjComboBox;
    private javax.swing.JComboBox eliminarTipoInstalacionjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList listEliminarInstalacion;
    private javax.swing.JPanel tFCantCancha;
    private javax.swing.JTextField tFCantGym;
    private javax.swing.JTextField tFCanttFNombrePiscina;
    private javax.swing.JTextField tFCanttFNombrePista;
    private javax.swing.JTextField tFCaracteristicasCancha;
    private javax.swing.JTextField tFCaracteristicasGym;
    private javax.swing.JTextField tFCaracteristicasPiscina;
    private javax.swing.JTextField tFCaracteristicastFNombrePista;
    private javax.swing.JTextField tFDimensionesCancha;
    private javax.swing.JTextField tFDimensionesGym;
    private javax.swing.JTextField tFDimensionesPiscina;
    private javax.swing.JTextField tFDimensionestFNombrePista;
    private javax.swing.JTextField tFNombreCancha;
    private javax.swing.JTextField tFNombreGym;
    private javax.swing.JTextField tFNombrePiscina;
    private javax.swing.JTextField tFNombrePista;
    private javax.swing.JTextField tFProdundidadPiscina;
    private javax.swing.JTextField tFtipoCancha;
    // End of variables declaration//GEN-END:variables
}
