/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import vista.*;
import controlador.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import sun.swing.plaf.synth.SynthIcon;
/**
 *
 * @author Mr.Kevin
 */
public class interfaz extends javax.swing.JFrame {
        
    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalsFrame = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInstalaciones = new javax.swing.JMenu();
        menuArticulo = new javax.swing.JMenu();
        socios = new javax.swing.JMenu();
        reservas = new javax.swing.JMenu();
        reporteDinamico = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout internalsFrameLayout = new javax.swing.GroupLayout(internalsFrame);
        internalsFrame.setLayout(internalsFrameLayout);
        internalsFrameLayout.setHorizontalGroup(
            internalsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 892, Short.MAX_VALUE)
        );
        internalsFrameLayout.setVerticalGroup(
            internalsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuInstalaciones.setText("Instalaciones");
        menuInstalaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInstalacionesMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuInstalaciones);

        menuArticulo.setText("Articulos");
        menuArticulo.setToolTipText("");
        menuArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuArticuloMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuArticulo);

        socios.setText("Socios");
        socios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sociosMouseClicked(evt);
            }
        });
        jMenuBar1.add(socios);

        reservas.setText("Reservas");
        reservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservasMouseClicked(evt);
            }
        });
        jMenuBar1.add(reservas);

        reporteDinamico.setText("Reportes Dinamicos");
        reporteDinamico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteDinamicoMouseClicked(evt);
            }
        });
        jMenuBar1.add(reporteDinamico);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(internalsFrame)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(internalsFrame)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuArticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuArticuloMouseClicked
        // TODO add your handling code here:
        articulo art =  new articulo();
        art.show();
        internalsFrame.add(art);
    }//GEN-LAST:event_menuArticuloMouseClicked

    private void sociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sociosMouseClicked
        // TODO add your handling code here:
        socios soc = new socios();
        soc.show();
        internalsFrame.add(soc);
    }//GEN-LAST:event_sociosMouseClicked

    private void menuInstalacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInstalacionesMouseClicked
        // TODO add your handling code here:
        instalaciones ins = new instalaciones();
        ins.show();
        internalsFrame.add(ins);
    }//GEN-LAST:event_menuInstalacionesMouseClicked

    private void reservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservasMouseClicked
        // TODO add your handling code here:
        reserva res = new reserva();
        res.show();
        internalsFrame.add(res);
    }//GEN-LAST:event_reservasMouseClicked

    private void reporteDinamicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteDinamicoMouseClicked
        // TODO add your handling code here:
        dinamica din = new dinamica();
        din.show();
        internalsFrame.add(din);
    }//GEN-LAST:event_reporteDinamicoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane internalsFrame;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArticulo;
    private javax.swing.JMenu menuInstalaciones;
    private javax.swing.JMenu reporteDinamico;
    private javax.swing.JMenu reservas;
    private javax.swing.JMenu socios;
    // End of variables declaration//GEN-END:variables
}
