/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import modelo.*;
import controlador.*;
import static controlador.Progra4.cenDep;
import javax.swing.DefaultListModel;
import vista.*;
/**
 *
 * @author Jona_RV
 */
public class reserva extends javax.swing.JInternalFrame {

    /**
     * Creates new form reserva
     */
    DefaultListModel list = new DefaultListModel();
    
    
    public reserva() {
        initComponents();
        socioVerReservasList.setModel(list);
        cargarSocioReservarCombobox();
        tipoInstalaReservarComboBoxActionPerformed(null);
        tipoArticuloComboBoxActionPerformed(null);
        socioVerReservaComboBoxActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrarFrameReserva = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        socioReservarComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFhoraInicioReserva = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFhoraFinReserva = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TFfechaReserva = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombreInstalaReservarComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        TFcedulaSocioReservar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TFcostoReserva = new javax.swing.JTextField();
        BTNreservarInstalacion = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tipoInstalaReservarComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        socioReservarArticuloComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TFcedulaSocioReservarArticulo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nombreInstalaReservarArticuloComboBox = new javax.swing.JComboBox();
        tipoArticuloComboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tipoArticuloReservaComboBox = new javax.swing.JComboBox();
        cantidadReservaArticuloSpinner = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        BTNreservarArticuloReserva = new javax.swing.JButton();
        TFfechaReservaArticulo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TFCostoReservaArticulo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        socioVerReservaComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        socioVerReservasList = new javax.swing.JList();

        cerrarFrameReserva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cerrarFrameReserva.setText("Cerrar");
        cerrarFrameReserva.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cerrarFrameReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarFrameReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarFrameReservaMouseClicked(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        socioReservarComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        socioReservarComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        socioReservarComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socioReservarComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Socio:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Hora Inicio:");

        TFhoraInicioReserva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Hora Fin:");

        TFhoraFinReserva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Fecha:");

        TFfechaReserva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nombre Instalacion:");

        nombreInstalaReservarComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreInstalaReservarComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Cedula:");

        TFcedulaSocioReservar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Costo:");

        TFcostoReserva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        BTNreservarInstalacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNreservarInstalacion.setText("Reservar");
        BTNreservarInstalacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNreservarInstalacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNreservarInstalacionMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Tipo Instalacion:");

        tipoInstalaReservarComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tipoInstalaReservarComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Piscinas", "Cancha", "Pista", "Gym" }));
        tipoInstalaReservarComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tipoInstalaReservarComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoInstalaReservarComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFfechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(socioReservarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(TFhoraInicioReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(TFhoraFinReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(TFcedulaSocioReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(TFcostoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(BTNreservarInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(tipoInstalaReservarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(nombreInstalaReservarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(socioReservarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TFcedulaSocioReservar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nombreInstalaReservarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tipoInstalaReservarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFhoraInicioReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TFhoraFinReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFfechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TFcostoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNreservarInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reserva Instalacion", jPanel1);

        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        socioReservarArticuloComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        socioReservarArticuloComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        socioReservarArticuloComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socioReservarArticuloComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Cedula:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Socio:");

        TFcedulaSocioReservarArticulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Nombre Instalacion Reservada:");

        nombreInstalaReservarArticuloComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreInstalaReservarArticuloComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tipoArticuloComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tipoArticuloComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Balon", "Raqueta", "Red" }));
        tipoArticuloComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoArticuloComboBoxActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Seleccione el Articulo:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Seleccione el tipo Articulo:");

        tipoArticuloReservaComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cantidadReservaArticuloSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Cantidad:");

        BTNreservarArticuloReserva.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTNreservarArticuloReserva.setText("Reservar Articulo");
        BTNreservarArticuloReserva.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNreservarArticuloReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNreservarArticuloReservaMouseClicked(evt);
            }
        });

        TFfechaReservaArticulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Fecha:");

        TFCostoReservaArticulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Costo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(socioReservarArticuloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(TFcedulaSocioReservarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFfechaReservaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoArticuloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoArticuloReservaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantidadReservaArticuloSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreInstalaReservarArticuloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(TFCostoReservaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)))
                        .addGap(25, 25, 25)
                        .addComponent(BTNreservarArticuloReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(TFcedulaSocioReservarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(socioReservarArticuloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(nombreInstalaReservarArticuloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TFfechaReservaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tipoArticuloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoArticuloReservaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadReservaArticuloSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(TFCostoReservaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(BTNreservarArticuloReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );

        jTabbedPane1.addTab("Reservar Articulo", jPanel2);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Socio:");

        socioVerReservaComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        socioVerReservaComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        socioVerReservaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socioVerReservaComboBoxActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(socioVerReservasList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(socioVerReservaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(socioVerReservaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver Reservas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cerrarFrameReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrarFrameReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarFrameReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarFrameReservaMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarFrameReservaMouseClicked

    private void socioReservarComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socioReservarComboBoxActionPerformed
        // TODO add your handling code here:
        int tam = cenDep.getListaSocios().size();
        
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                if(socioReservarComboBox.getSelectedItem().equals(cenDep.getListaSocios().get(i).getNombre())){
                    TFcedulaSocioReservar.setText(cenDep.getListaSocios().get(i).getIdSocio());
                }
            }
        }
    }//GEN-LAST:event_socioReservarComboBoxActionPerformed

    private void tipoInstalaReservarComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoInstalaReservarComboBoxActionPerformed
        // TODO add your handling code here:
        nombreInstalaReservarComboBox.removeAllItems();
        int tam = Progra4.cenDep.getListaInstalaciones().size();
        
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                String[] nombreClase = Progra4.cenDep.getListaInstalaciones().get(i).getClass().getName().split("controlador.");
                if(nombreClase[1].equals(tipoInstalaReservarComboBox.getSelectedItem()))
                {
                    nombreInstalaReservarComboBox.addItem(Progra4.cenDep.getListaInstalaciones().get(i).getNombre());
                }                
             }
        }
    }//GEN-LAST:event_tipoInstalaReservarComboBoxActionPerformed

    private void BTNreservarInstalacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNreservarInstalacionMouseClicked
        // TODO add your handling code here:
        String cedulaSocio = TFcedulaSocioReservar.getText();
        String nomInstalacion = nombreInstalaReservarComboBox.getSelectedItem().toString();
        String horaInicio = TFhoraInicioReserva.getText();
        String horaFin = TFhoraFinReserva.getText();
        String fecha = TFfechaReserva.getText();
        int costo = Integer.parseInt(TFcostoReserva.getText());
        
        metodosBase.insertarReservaInstalacionBase(cedulaSocio, nomInstalacion, horaInicio, horaFin, fecha, costo);
    }//GEN-LAST:event_BTNreservarInstalacionMouseClicked

    private void socioReservarArticuloComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socioReservarArticuloComboBoxActionPerformed
        // TODO add your handling code here:
        int tam = cenDep.getListaSocios().size();
        
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                if(socioReservarArticuloComboBox.getSelectedItem().equals(cenDep.getListaSocios().get(i).getNombre())){
                    TFcedulaSocioReservarArticulo.setText(cenDep.getListaSocios().get(i).getIdSocio());
                    cargarNombreInstalaReserArticulo();
                }
            }
        }
    }//GEN-LAST:event_socioReservarArticuloComboBoxActionPerformed

    private void tipoArticuloComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoArticuloComboBoxActionPerformed
        // TODO add your handling code here:
        tipoArticuloReservaComboBox.removeAllItems();
        int tam = cenDep.getListaArticulos().size();

        if(tam > 0){
            for(int i = 0; i < tam; i++){
                if(tipoArticuloComboBox.getSelectedItem().equals(cenDep.getListaArticulos().get(i).getNombre()))
                {
                    tipoArticuloReservaComboBox.addItem(cenDep.getListaArticulos().get(i).getTipo());
                }
            }
        }
    }//GEN-LAST:event_tipoArticuloComboBoxActionPerformed

    private void BTNreservarArticuloReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNreservarArticuloReservaMouseClicked
        // TODO add your handling code here:
        String cedulaSocio = TFcedulaSocioReservarArticulo.getText();
        String nomArt = tipoArticuloComboBox.getSelectedItem().toString();
        String tipoArt = tipoArticuloReservaComboBox.getSelectedItem().toString();
        String fecha = TFfechaReservaArticulo.getText();
        int cantidad = Integer.parseInt(cantidadReservaArticuloSpinner.getValue().toString());
        int costo = Integer.parseInt(TFCostoReservaArticulo.getText());
        
        metodosBase.insertarReservaArticuloInstalacionBase(cedulaSocio, nomArt, tipoArt, fecha, cantidad, costo);
    }//GEN-LAST:event_BTNreservarArticuloReservaMouseClicked

    private void socioVerReservaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socioVerReservaComboBoxActionPerformed
        // TODO add your handling code here:
        list.clear();
        int tam = cenDep.getListaReserva().size();
        int tamS = cenDep.getListaSocios().size();
        
        if(tam > 0){
            for(int j = 0; j < tamS; j++){
                if(socioVerReservaComboBox.getSelectedItem().equals(cenDep.getListaSocios().get(j).getNombre())){
                    for(int i = 0; i < tam; i++){
                        if(cenDep.getListaReserva().get(i).getCedulaSocio().equals(cenDep.getListaSocios().get(j).getIdSocio())){
                            list.addElement("Nombre Instalacion: "+cenDep.getListaReserva().get(i).getNomInstalacion());
                            list.addElement("Hora Inicio:   "+cenDep.getListaReserva().get(i).getHoraInicio());
                            list.addElement("Hora Fin:   "+cenDep.getListaReserva().get(i).getHoraFin());
                            list.addElement("Fecha:     "+cenDep.getListaReserva().get(i).getFecha());
                            list.addElement("Costo:     "+cenDep.getListaReserva().get(i).getCosto());
                            list.addElement("");
                            list.addElement("***************** Articulos ********************");
                            list.addElement("");

                            int tamRA = cenDep.getListaReserva().get(i).getListaReservaArticulos().size();
                            if(tamRA > 0){
                                for(int y = 0; y < tamRA; y++){
                                    list.addElement("Articulo:    "+cenDep.getListaReserva().get(i).getListaReservaArticulos().get(y).getNombreArt());
                                    list.addElement("Tipo Articulo: "+cenDep.getListaReserva().get(i).getListaReservaArticulos().get(y).getTipoArt());
                                    list.addElement("Cantidad:   "+cenDep.getListaReserva().get(i).getListaReservaArticulos().get(y).getCantidad());
                                }
                            }
                        }
                    }
                }
            }
        }        
    }//GEN-LAST:event_socioVerReservaComboBoxActionPerformed

    
    public void cargarSocioReservarCombobox(){
        
        int tam = cenDep.getListaSocios().size();
        
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                socioReservarComboBox.addItem(cenDep.getListaSocios().get(i).getNombre());
                socioReservarArticuloComboBox.addItem(cenDep.getListaSocios().get(i).getNombre());
                socioVerReservaComboBox.addItem(cenDep.getListaSocios().get(i).getNombre());
            }
        }
    }
    
    public void cargarNombreInstalaReserArticulo(){
        nombreInstalaReservarArticuloComboBox.removeAllItems();
        int tam = cenDep.getListaReserva().size();
        System.out.print(tam);
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                if(TFcedulaSocioReservarArticulo.getText().equals(cenDep.getListaReserva().get(i).getCedulaSocio())){
                    nombreInstalaReservarArticuloComboBox.addItem(cenDep.getListaReserva().get(i).getNomInstalacion());
                }
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNreservarArticuloReserva;
    private javax.swing.JButton BTNreservarInstalacion;
    private javax.swing.JTextField TFCostoReservaArticulo;
    private javax.swing.JTextField TFcedulaSocioReservar;
    private javax.swing.JTextField TFcedulaSocioReservarArticulo;
    private javax.swing.JTextField TFcostoReserva;
    private javax.swing.JTextField TFfechaReserva;
    private javax.swing.JTextField TFfechaReservaArticulo;
    private javax.swing.JTextField TFhoraFinReserva;
    private javax.swing.JTextField TFhoraInicioReserva;
    private javax.swing.JSpinner cantidadReservaArticuloSpinner;
    private javax.swing.JButton cerrarFrameReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox nombreInstalaReservarArticuloComboBox;
    private javax.swing.JComboBox nombreInstalaReservarComboBox;
    private javax.swing.JComboBox socioReservarArticuloComboBox;
    private javax.swing.JComboBox socioReservarComboBox;
    private javax.swing.JComboBox socioVerReservaComboBox;
    private javax.swing.JList socioVerReservasList;
    private javax.swing.JComboBox tipoArticuloComboBox;
    private javax.swing.JComboBox tipoArticuloReservaComboBox;
    private javax.swing.JComboBox tipoInstalaReservarComboBox;
    // End of variables declaration//GEN-END:variables
}
