/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.*;
import modelo.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import vista.*;
/**
 *
 * @author Jona_RV
 */
public class socios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Socios
     */
    public socios() {
        initComponents();
        int tam = Progra4.cenDep.getListaSocios().size();
        
        if(tam > 0){
            for(int i = 0; i < tam; i++){
                socioEliminarCombobox.addItem(Progra4.cenDep.getListaSocios().get(i).getNombre());
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        nombreSocioAgregarTextField = new javax.swing.JTextField();
        cedulaSocioAgregarTextField = new javax.swing.JTextField();
        telefonoSocioAgregarTextField = new javax.swing.JTextField();
        provinciaSocioAgregarTextField = new javax.swing.JTextField();
        ciudadSocioAgregarTextField = new javax.swing.JTextField();
        direccionSocioAgregarTextField = new javax.swing.JTextField();
        cuotaSocioAgregarTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        agregarSocioAgregarBoton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        socioEliminarCombobox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        eliminarSocioEliminarBoton = new javax.swing.JButton();
        cerrarSociosFrame = new javax.swing.JButton();

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nombreSocioAgregarTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cedulaSocioAgregarTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        telefonoSocioAgregarTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        provinciaSocioAgregarTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        provinciaSocioAgregarTextField.setToolTipText("");

        ciudadSocioAgregarTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        direccionSocioAgregarTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cuotaSocioAgregarTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nombre:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Cedula:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Telefono:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Provincia:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Ciudad:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Direccion:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Cuota Mes:");

        agregarSocioAgregarBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        agregarSocioAgregarBoton.setText("Agregar");
        agregarSocioAgregarBoton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agregarSocioAgregarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarSocioAgregarBotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(agregarSocioAgregarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(provinciaSocioAgregarTextField)
                            .addComponent(nombreSocioAgregarTextField)
                            .addComponent(cuotaSocioAgregarTextField)
                            .addComponent(cedulaSocioAgregarTextField)
                            .addComponent(direccionSocioAgregarTextField)
                            .addComponent(ciudadSocioAgregarTextField)
                            .addComponent(telefonoSocioAgregarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreSocioAgregarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaSocioAgregarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoSocioAgregarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provinciaSocioAgregarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudadSocioAgregarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionSocioAgregarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuotaSocioAgregarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(27, 27, 27)
                .addComponent(agregarSocioAgregarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("Agregar Socio", jPanel3);

        socioEliminarCombobox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        socioEliminarCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socioEliminarComboboxActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Seleccione el Socio:");

        eliminarSocioEliminarBoton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        eliminarSocioEliminarBoton.setText("Eliminar");
        eliminarSocioEliminarBoton.setToolTipText("");
        eliminarSocioEliminarBoton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarSocioEliminarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarSocioEliminarBotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eliminarSocioEliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(40, 40, 40)
                        .addComponent(socioEliminarCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(165, 165, 165))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(socioEliminarCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(56, 56, 56)
                .addComponent(eliminarSocioEliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Socio", jPanel4);

        cerrarSociosFrame.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cerrarSociosFrame.setText("Cerrar");
        cerrarSociosFrame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cerrarSociosFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSociosFrameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrarSociosFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrarSociosFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSociosFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSociosFrameMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarSociosFrameMouseClicked

    private void agregarSocioAgregarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarSocioAgregarBotonMouseClicked
        // TODO add your handling code here:
        
        String nombre = nombreSocioAgregarTextField.getText();
        String cedula = cedulaSocioAgregarTextField.getText();
        String telefono = telefonoSocioAgregarTextField.getText();
        String provincia = provinciaSocioAgregarTextField.getText();
        String ciudad = ciudadSocioAgregarTextField.getText();
        String direccion = direccionSocioAgregarTextField.getText();
        int cuota = Integer.parseInt(cuotaSocioAgregarTextField.getText());
        
        Socios per = new Socios(nombre, cedula, telefono, provincia, ciudad, direccion, cuota);
        Progra4.cenDep.getListaSocios().add(per);
        
        metodosBase met = new metodosBase();
        met.insertarSocioBase(nombre, cedula, telefono, provincia, ciudad, direccion, cuota);
        
        cargarComboboxSocios();
        
        nombreSocioAgregarTextField.setText("");
        cedulaSocioAgregarTextField.setText("");
        telefonoSocioAgregarTextField.setText("");
        provinciaSocioAgregarTextField.setText("");
        ciudadSocioAgregarTextField.setText("");
        direccionSocioAgregarTextField.setText("");
        cuotaSocioAgregarTextField.setText("");
    }//GEN-LAST:event_agregarSocioAgregarBotonMouseClicked

    private void socioEliminarComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socioEliminarComboboxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_socioEliminarComboboxActionPerformed

    private void eliminarSocioEliminarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarSocioEliminarBotonMouseClicked
        // TODO add your handling code here:
  
        if(!(socioEliminarCombobox.getSelectedItem().equals(""))){
            for(int i = 0; i < Progra4.cenDep.getListaSocios().size(); i++){
                if(socioEliminarCombobox.getSelectedItem().equals(Progra4.cenDep.getListaSocios().get(i).getNombre())){
                    metodosBase met = new metodosBase();
                    met.eliminarSocioBase(Progra4.cenDep.getListaSocios().get(i).getIdSocio());
                    Progra4.cenDep.getListaSocios().remove(i);
                    cargarComboboxSocios();
                }
            }
        }
    }//GEN-LAST:event_eliminarSocioEliminarBotonMouseClicked


    public void cargarComboboxSocios(){
        
        socioEliminarCombobox.removeAllItems();
        int tam = Progra4.cenDep.getListaSocios().size();
                
        for(int i = 0; i < tam; i++){
            socioEliminarCombobox.addItem(Progra4.cenDep.getListaSocios().get(i).getNombre());
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarSocioAgregarBoton;
    private javax.swing.JTextField cedulaSocioAgregarTextField;
    private javax.swing.JButton cerrarSociosFrame;
    private javax.swing.JTextField ciudadSocioAgregarTextField;
    private javax.swing.JTextField cuotaSocioAgregarTextField;
    private javax.swing.JTextField direccionSocioAgregarTextField;
    private javax.swing.JButton eliminarSocioEliminarBoton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nombreSocioAgregarTextField;
    private javax.swing.JTextField provinciaSocioAgregarTextField;
    private javax.swing.JComboBox socioEliminarCombobox;
    private javax.swing.JTextField telefonoSocioAgregarTextField;
    // End of variables declaration//GEN-END:variables
}
